# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infaCliResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='infaCliResponse.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15infaCliResponse.proto\"\x92\x01\n\x0fInfaCliResponse\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x30\n\x08messages\x18\x03 \x03(\x0b\x32\x1e.InfaCliResponse.ExtraMessages\x1a,\n\rExtraMessages\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')
)




_INFACLIRESPONSE_EXTRAMESSAGES = _descriptor.Descriptor(
  name='ExtraMessages',
  full_name='InfaCliResponse.ExtraMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='InfaCliResponse.ExtraMessages.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='InfaCliResponse.ExtraMessages.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=172,
)

_INFACLIRESPONSE = _descriptor.Descriptor(
  name='InfaCliResponse',
  full_name='InfaCliResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retcode', full_name='InfaCliResponse.retcode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='InfaCliResponse.stdout', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='InfaCliResponse.messages', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFACLIRESPONSE_EXTRAMESSAGES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=172,
)

_INFACLIRESPONSE_EXTRAMESSAGES.containing_type = _INFACLIRESPONSE
_INFACLIRESPONSE.fields_by_name['messages'].message_type = _INFACLIRESPONSE_EXTRAMESSAGES
DESCRIPTOR.message_types_by_name['InfaCliResponse'] = _INFACLIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InfaCliResponse = _reflection.GeneratedProtocolMessageType('InfaCliResponse', (_message.Message,), dict(

  ExtraMessages = _reflection.GeneratedProtocolMessageType('ExtraMessages', (_message.Message,), dict(
    DESCRIPTOR = _INFACLIRESPONSE_EXTRAMESSAGES,
    __module__ = 'infaCliResponse_pb2'
    # @@protoc_insertion_point(class_scope:InfaCliResponse.ExtraMessages)
    ))
  ,
  DESCRIPTOR = _INFACLIRESPONSE,
  __module__ = 'infaCliResponse_pb2'
  # @@protoc_insertion_point(class_scope:InfaCliResponse)
  ))
_sym_db.RegisterMessage(InfaCliResponse)
_sym_db.RegisterMessage(InfaCliResponse.ExtraMessages)


# @@protoc_insertion_point(module_scope)
